name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Cython==0.29.33 buildozer

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK
        run: |
          # 设置 Android SDK 路径
          ANDROID_HOME=/usr/local/lib/android/sdk
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          
          # 创建目录结构
          sudo mkdir -p $ANDROID_HOME
          sudo chown -R runner:runner $ANDROID_HOME
          
          # 安装必要依赖
          sudo apt-get update && sudo apt-get install -y \
            unzip \
            libc6-i386 \
            lib32stdc++6 \
            lib32z1 \
            zlib1g-dev

          # 下载命令行工具
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-*.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          rm commandlinetools-linux-*.zip

          # 接受许可证
          mkdir -p $ANDROID_HOME/licenses
          echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license
          echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license

          # 安装组件
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME \
            "platform-tools" \
            "build-tools;33.0.2" \
            "platforms;android-33" \
            "cmdline-tools;latest"

          # 创建兼容旧版路径的目录结构
          mkdir -p $ANDROID_HOME/tools
          ln -s $ANDROID_HOME/cmdline-tools/latest/bin $ANDROID_HOME/tools/bin

      - name: Configure Buildozer environment
        run: |
          # 完全禁用 Buildozer 的自动 SDK 安装
          mkdir -p ~/.buildozer/android/platform
          echo "android.sdk_path = /usr/local/lib/android/sdk" > ~/.buildozer/android/platform/buildozer.ini
          echo "android.ndk_path = $HOME/.buildozer/android/platform/android-ndk-r25b" >> ~/.buildozer/android/platform/buildozer.ini
          
          # 预下载 NDK
          NDK_DIR="$HOME/.buildozer/android/platform/android-ndk-r25b"
          if [ ! -d "$NDK_DIR" ]; then
            wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
            unzip -q android-ndk-r25b-linux.zip -d ~/.buildozer/android/platform/
            rm android-ndk-r25b-linux.zip
          fi

      - name: Initialize Buildozer
        run: |
          buildozer init
          # 强制修正所有路径配置
          sed -i "s|^android.sdk_path =.*|android.sdk_path = /usr/local/lib/android/sdk|" buildozer.spec
          sed -i "s|^android.ndk_path =.*|android.ndk_path = $HOME/.buildozer/android/platform/android-ndk-r25b|" buildozer.spec
          sed -i "s|^p4a.branch =.*|p4a.branch = develop|" buildozer.spec
          sed -i "s|^#android.accept_sdk_license =.*|android.accept_sdk_license = True|" buildozer.spec
          sed -i "s|^#log_level =.*|log_level = 2|" buildozer.spec

      - name: Modify buildozer.spec
        run: |
          sed -i 's/package.name = myapp/package.name = pythonapp/' buildozer.spec
          sed -i 's/package.domain = org.example/package.domain = com.example/' buildozer.spec
          sed -i 's/source.dir =.*/source.dir = ./' buildozer.spec
          sed -i 's/requirements =.*/requirements = python3,kivy/' buildozer.spec
          sed -i 's/android.build_tools_version =.*/android.build_tools_version = 33.0.2/' buildozer.spec
          sed -i 's/android.api =.*/android.api = 33/' buildozer.spec

      - name: Build APK
        run: |
          # 调试信息
          echo "=== 验证 SDK 路径 ==="
          ls -la /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager
          ls -la /usr/local/lib/android/sdk/tools/bin/sdkmanager
          
          echo "=== 构建环境 ==="
          buildozer --version
          buildozer android --help
          
          # 构建 APK
          buildozer -v android debug 2>&1 | tee build.log
          grep -i "error" build.log && exit 1 || true
          
          # 收集产物
          mkdir -p artifacts
          cp bin/*.apk artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifacts
          path: |
            artifacts/
            build.log
