name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean environment
        run: |
          rm -f buildozer.spec
          rm -rf .buildozer
          rm -rf bin

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Cython==0.29.33 buildozer

      - name: Create buildozer.spec
        run: |
          cat <<EOF > buildozer.spec
          [app]
          # 应用配置
          title = MyApp
          package.name = pythonapp
          package.domain = com.example
          source.dir = .
          requirements = python3,kivy
          
          # 必须的版本配置（修复关键错误）
          version = 0.1
          
          # Android 配置
          android.sdk_path = /usr/local/lib/android/sdk
          android.ndk_path = /home/runner/.buildozer/android/platform/android-ndk-r25b
          android.build_tools_version = 33.0.2
          android.api = 33
          p4a.branch = develop
          android.accept_sdk_license = True

          [buildozer]
          log_level = 2
          EOF

      - name: Verify spec file
        run: |
          echo "=== buildozer.spec 验证 ==="
          grep -A2 "\[app\]" buildozer.spec
          grep "version" buildozer.spec || echo "错误：缺少版本配置"

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK
        run: |
          ANDROID_HOME=/usr/local/lib/android/sdk
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          
          sudo mkdir -p $ANDROID_HOME
          sudo chown -R runner:runner $ANDROID_HOME
          
          sudo apt-get update && sudo apt-get install -y \
            unzip \
            libc6-i386 \
            lib32stdc++6 \
            lib32z1 \
            zlib1g-dev

          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-*.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          rm commandlinetools-linux-*.zip

          mkdir -p $ANDROID_HOME/licenses
          echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license
          echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license

          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME \
            "platform-tools" \
            "build-tools;33.0.2" \
            "platforms;android-33" \
            "cmdline-tools;latest"

          mkdir -p $ANDROID_HOME/tools
          ln -s $ANDROID_HOME/cmdline-tools/latest/bin $ANDROID_HOME/tools/bin

      - name: Install NDK
        run: |
          mkdir -p ~/.buildozer/android/platform
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip -d ~/.buildozer/android/platform/
          rm android-ndk-r25b-linux.zip

      - name: Build APK
        run: |
          mkdir -p bin
          
          echo "=== 开始构建 ==="
          buildozer -v android debug 2>&1 | tee build.log
          
          if [ $? -ne 0 ]; then
            echo "构建失败！最后10行日志："
            tail -n 10 build.log
            exit 1
          fi
          
          if [ ! -f bin/*.apk ]; then
            echo "错误：未生成APK文件！完整日志："
            cat build.log
            exit 1
          fi

          mkdir -p artifacts
          cp bin/*.apk artifacts/

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifacts
          path: artifacts/
