name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Cython==0.29.33 buildozer

      - name: Set up Android SDK and accept licenses
        uses: android-actions/setup-android-sdk@v3
        with:
          android-sdk-version: 33
          android-components: |
            build-tools;33.0.2
            platforms;android-33
            tools
        env:
          ANDROID_ACCEPT_LICENSE: "yes"

      - name: Initialize Buildozer
        run: buildozer init

      - name: Modify buildozer.spec
        run: |
          sed -i 's/package.name = myapp/package.name = pythonapp/' buildozer.spec
          sed -i 's/package.domain = org.example/package.domain = com.example/' buildozer.spec
          sed -i 's/source.dir =.*/source.dir = ./' buildozer.spec
          sed -i 's/requirements =.*/requirements = python3,kivy/' buildozer.spec
          sed -i 's/main\.py/main.py/' buildozer.spec

      - name: Build APK
        run: |
          buildozer -v android debug
          mkdir artifacts
          cp bin/*.apk artifacts/

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app-apk
          path: artifacts/
