name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug - List project directory
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          ls -la $GITHUB_WORKSPACE

      - name: Clean environment
        run: |
          sudo rm -rf /usr/local/lib/android/sdk
          rm -rf $GITHUB_WORKSPACE/.buildozer $GITHUB_WORKSPACE/bin
          echo "环境清理完成"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Enable i386 architecture
        run: |
          sudo dpkg --add-architecture i386
          echo "i386 架构已启用"

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            unzip \
            libc6:i386 \
            lib32stdc++6 \
            lib32z1 \
            zlib1g-dev \
            libncurses6:i386 \
            libstdc++-12-dev \
            libstdc++-12-dev:i386 \
            libx11-6:i386 \
            gcc-multilib \
            g++-multilib \
            autogen \
            autoconf \
            automake \
            libtool \
            libtool-bin \
            openjdk-11-jdk \
            ccache
          
          # 更新 autotools
          sudo apt-get install -y autoconf automake libtool
          sudo apt-get upgrade -y autoconf automake libtool
          
          # 验证依赖项是否安装成功
          echo "=== 依赖项验证 ==="
          dpkg -l | grep -E "libtool|autoconf|automake|openjdk-11"
          
          if ! command -v libtool &> /dev/null; then
            echo "尝试通过libtoolize访问libtool功能"
            if command -v libtoolize &> /dev/null; then
              echo "libtoolize可用，创建符号链接"
              sudo ln -s "$(which libtoolize)" /usr/bin/libtool
            else
              echo "错误: libtool和libtoolize均未找到"
              exit 1
            fi
          fi
          
          if ! command -v libtool &> /dev/null; then
            echo "错误: libtool 未正确安装"
            exit 1
          fi
          
          echo "系统依赖安装完成"
          echo "libtool版本: $(libtool --version | head -n1)"
          echo "Java版本: $(java -version 2>&1 | head -n1)"

      - name: Create buildozer.spec
        run: |
          cat <<EOF > $GITHUB_WORKSPACE/buildozer.spec
          [app]
          title = MyApp
          package.name = pythonapp
          package.domain = com.example
          source.dir = .
          requirements = python3,kivy
          version = 0.1
          
          # Android配置
          android.sdk_path = /usr/local/lib/android/sdk
          android.ndk_path = /usr/local/lib/android/sdk/ndk/25.2.9519653
          android.build_tools_version = 33.0.2
          android.api = 33
          android.minapi = 21
          android.ndk_api = 23
          android.accept_sdk_license = True
          android.archs = arm64-v8a,armeabi-v7a

          [buildozer]
          log_level = 2
          warn_on_root = False
          EOF
          echo "buildozer.spec 创建成功"

      - name: Create Gradle wrapper properties
        run: |
          mkdir -p $GITHUB_WORKSPACE/gradle/wrapper
          cat <<EOF > $GITHUB_WORKSPACE/gradle/wrapper/gradle-wrapper.properties
          distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists
          EOF
          echo "gradle-wrapper.properties 创建成功"

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Install Android SDK
        run: |
          ANDROID_HOME=/usr/local/lib/android/sdk
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
          
          sudo mkdir -p $ANDROID_HOME
          sudo chown -R runner:runner $ANDROID_HOME
          
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O /tmp/cmdline-tools.zip
          unzip -q /tmp/cmdline-tools.zip -d /tmp/cmdline-tools
          
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          mv /tmp/cmdline-tools/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/
          rm -rf /tmp/cmdline-tools*

          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses || true

          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME \
            "platform-tools" \
            "build-tools;33.0.2" \
            "platforms;android-33" \
            "cmdline-tools;latest" \
            "ndk;25.2.9519653"

          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list --sdk_root=$ANDROID_HOME
          echo "Android SDK 安装验证通过"

      - name: Configure NDK
        run: |
          ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/25.2.9519653
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_NDK_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK=$ANDROID_NDK_HOME" >> $GITHUB_ENV
          
          rm -rf /home/runner/.buildozer/android/platform/android-ndk-r25b
          
          echo "NDK 配置完成"

      - name: Pre-build verification
        run: |
          echo "=== 关键路径验证 ==="
          ls -la /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager
          ls -la /usr/local/lib/android/sdk/tools/bin/sdkmanager || echo "旧路径不存在（符合预期）"
          ls -la /usr/local/lib/android/sdk/ndk/25.2.9519653/ndk-build
          
          echo "=== 环境变量 ==="
          echo "ANDROID_HOME=$ANDROID_HOME"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME"
          echo "ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT"
          echo "ANDROID_NDK=$ANDROID_NDK"
          echo "JAVA_HOME=$JAVA_HOME"
          echo "PATH=$PATH"
          
          echo "=== SDK组件列表 ==="
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list --sdk_root=$ANDROID_HOME
          
          echo "=== C++ 编译器验证 ==="
          g++ --version
          echo "32位库验证:"
          dpkg -l | grep libstdc++
          
          echo "=== Autotools 验证 ==="
          autoconf --version
          automake --version
          libtool --version
          
          echo "=== Java 验证 ==="
          java -version

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade cython buildozer python-for-android
          echo "Cython 安装完成，版本: $(cython --version)"
          buildozer --version
          p4a --version

      - name: Fix Python-for-Android patches
        run: |
          # 修复hostpython3补丁问题
          P4A_DIR="$GITHUB_WORKSPACE/.buildozer/android/platform/python-for-android"
          if [ -d "$P4A_DIR" ]; then
            # 创建补丁目录（如果不存在）
            mkdir -p "$P4A_DIR/pythonforandroid/recipes/hostpython3/patches"
            
            # 更新hostpython3补丁以兼容Python 3.11.5
            cat > "$P4A_DIR/pythonforandroid/recipes/hostpython3/patches/pyconfig_detection.patch" << 'EOPATCH'
            diff -Nru Python-3.11.5/Lib/site.py Python-3.11.5-new/Lib/site.py
            --- Python-3.11.5/Lib/site.py    2023-08-24 12:48:38.000000000 -0700
            +++ Python-3.11.5-new/Lib/site.py        2023-08-24 12:52:46.000000000 -0700
            @@ -300,6 +300,9 @@
                 if ENABLE_USER_SITE and os.path.isdir(user_site):
                     addsitedir(user_site, known_paths)
             
            +    # Add the build directory to sys.path
            +    addsitedir(os.path.dirname(os.path.abspath(__file__)), known_paths)
            +
                 # Set sys.argv[0]
                 if sys.argv[0] == '-c':
                     # -c option: set sys.argv[0] to '' (issue #18124)
            EOPATCH
            echo "已更新hostpython3补丁文件"
          else
            echo "未找到python-for-android目录，跳过补丁更新"
          fi
          
      - name: Build APK
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          
          export ANDROID_HOME=$ANDROID_HOME
          export ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT
          export ANDROID_NDK_HOME=$ANDROID_NDK_HOME
          export ANDROID_NDK_ROOT=$ANDROID_NDK_HOME
          export ANDROID_NDK=$ANDROID_NDK_HOME
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          
          echo "=== 构建环境验证 ==="
          echo "ANDROID_HOME=$ANDROID_HOME"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME"
          echo "ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT"
          echo "ANDROID_NDK=$ANDROID_NDK"
          echo "PATH=$PATH"
          
          echo "=== sdkmanager路径验证 ==="
          which sdkmanager
          ls -la $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager
          
          mkdir -p $ANDROID_HOME/tools/bin
          ln -s $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager $ANDROID_HOME/tools/bin/sdkmanager
          echo "创建了从旧路径到新路径的符号链接"
          
          echo "=== 符号链接验证 ==="
          ls -la $ANDROID_HOME/tools/bin/sdkmanager
          
          echo "=== NDK验证 ==="
          ls -la $ANDROID_NDK_HOME/ndk-build
          
          # 确保构建目录存在
          mkdir -p $GITHUB_WORKSPACE/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Modules
          
          # 构建命令
          cd $GITHUB_WORKSPACE
          buildozer -v -f android debug --storage-dir=$GITHUB_WORKSPACE/.buildozer/android/platform/build
          
          if [ ! -f $GITHUB_WORKSPACE/bin/*.apk ]; then
            echo "=== 构建失败分析 ==="
            echo "最后200行日志："
            tail -n 200 build.log
            echo "常见问题排查："
            echo "1. 检查是否缺少依赖库：sudo apt-get install libc6:i386 libstdc++-12-dev libstdc++-12-dev:i386"
            echo "2. 确认ANDROID_HOME路径正确：ls -la $ANDROID_HOME"
            echo "3. 验证平台工具版本：确保android.api=33对应platforms;android-33"
            echo "4. 检查NDK安装：ls -la $ANDROID_NDK_HOME"
            exit 1
          fi

          mkdir -p $GITHUB_WORKSPACE/artifacts
          cp $GITHUB_WORKSPACE/bin/*.apk $GITHUB_WORKSPACE/artifacts/
          echo "APK构建成功！"

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifacts
          path: $GITHUB_WORKSPACE/artifacts/
