name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug - List project directory
        run: |
          ls -la

      - name: Clean environment
        run: |
          sudo rm -rf /usr/local/lib/android/sdk
          rm -rf .buildozer bin
          echo "环境清理完成"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Enable i386 architecture
        run: |
          sudo dpkg --add-architecture i386
          echo "i386 架构已启用"

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            unzip \
            libc6:i386 \
            lib32stdc++6 \
            lib32z1 \
            zlib1g-dev \
            libncurses6:i386 \
            libstdc++-12-dev \
            libstdc++-12-dev:i386 \
            libx11-6:i386 \
            gcc-multilib \
            g++-multilib \
            autogen \
            autoconf \
            automake \
            libtool
          
          # 验证依赖项是否安装成功
          echo "=== 依赖项验证 ==="
          dpkg -l | grep -E "libtool|autoconf|automake"
          
          if ! command -v libtool &> /dev/null; then
            echo "错误: libtool 未安装"
            exit 1
          fi
          
          echo "系统依赖安装完成"

      - name: Create buildozer.spec
        run: |
          cat <<EOF > buildozer.spec
          [app]
          title = MyApp
          package.name = pythonapp
          package.domain = com.example
          source.dir = .
          requirements = python3,kivy
          version = 0.1
          
          # Android配置
          android.sdk_path = /usr/local/lib/android/sdk
          android.ndk_path = /home/runner/.buildozer/android/platform/android-ndk-r25b
          android.build_tools_version = 33.0.2
          android.api = 33
          android.minapi = 21
          android.ndk_api = 23
          android.accept_sdk_license = True

          [buildozer]
          log_level = 2
          EOF
          echo "buildozer.spec 创建成功"

      - name: Create Gradle wrapper properties
        run: |
          mkdir -p gradle/wrapper
          cat <<EOF > gradle/wrapper/gradle-wrapper.properties
          distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists
          EOF
          echo "gradle-wrapper.properties 创建成功"

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Install Android SDK
        run: |
          ANDROID_HOME=/usr/local/lib/android/sdk
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
          
          # 创建干净的目录结构
          sudo mkdir -p $ANDROID_HOME
          sudo chown -R runner:runner $ANDROID_HOME
          
          # 安装命令行工具
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O /tmp/cmdline-tools.zip
          unzip -q /tmp/cmdline-tools.zip -d /tmp/cmdline-tools
          
          # 移动文件到正确位置
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          mv /tmp/cmdline-tools/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/
          rm -rf /tmp/cmdline-tools*

          # 配置环境变量
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

          # 接受许可证
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses || true

          # 安装核心组件
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME \
            "platform-tools" \
            "build-tools;33.0.2" \
            "platforms;android-33" \
            "cmdline-tools;latest"

          # 验证安装
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list --sdk_root=$ANDROID_HOME
          echo "Android SDK 安装验证通过"

      - name: Install NDK
        run: |
          mkdir -p ~/.buildozer/android/platform
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip -d ~/.buildozer/android/platform/
          rm android-ndk-r25b-linux.zip
          
          # 设置NDK环境变量
          echo "ANDROID_NDK_HOME=/home/runner/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=/home/runner/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          echo "ANDROID_NDK=/home/runner/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          
          echo "NDK r25b 安装完成"

      - name: Pre-build verification
        run: |
          echo "=== 关键路径验证 ==="
          ls -la /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager
          ls -la /usr/local/lib/android/sdk/tools/bin/sdkmanager || echo "旧路径不存在（符合预期）"
          ls -la /home/runner/.buildozer/android/platform/android-ndk-r25b/ndk-build || echo "NDK 构建工具不存在"
          
          echo "=== 环境变量 ==="
          echo "ANDROID_HOME=$ANDROID_HOME"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          echo "JAVA_HOME=$JAVA_HOME"
          echo "PATH=$PATH"
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME"
          echo "ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT"
          echo "ANDROID_NDK=$ANDROID_NDK"
          
          echo "=== SDK组件列表 ==="
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list --sdk_root=$ANDROID_HOME
          
          echo "=== C++ 编译器验证 ==="
          g++ --version
          echo "32位库验证:"
          dpkg -l | grep libstdc++
          
          echo "=== Autotools 验证 ==="
          autoconf --version
          automake --version
          libtool --version  # 这行之前可能导致错误，现在确保libtool已安装

      - name: Install Buildozer and dependencies
        run: |
          # 先安装Cython
          pip install --upgrade cython
          echo "Cython 安装完成，版本: $(cython --version)"
          
          # 再安装Buildozer
          pip install --upgrade buildozer
          buildozer --version

      - name: Build APK
        run: |
          mkdir -p bin
          
          # 确保所有环境变量在当前shell中也可用
          export ANDROID_HOME=$ANDROID_HOME
          export ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT
          export ANDROID_NDK_HOME=/home/runner/.buildozer/android/platform/android-ndk-r25b
          export ANDROID_NDK_ROOT=/home/runner/.buildozer/android/platform/android-ndk-r25b
          export ANDROID_NDK=/home/runner/.buildozer/android/platform/android-ndk-r25b
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          
          # 验证环境变量
          echo "=== 构建环境验证 ==="
          echo "ANDROID_HOME=$ANDROID_HOME"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME"
          echo "ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT"
          echo "ANDROID_NDK=$ANDROID_NDK"
          echo "PATH=$PATH"
          
          # 验证sdkmanager路径
          echo "=== sdkmanager路径验证 ==="
          which sdkmanager
          ls -la $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager
          
          # 创建符号链接，使旧路径指向新路径
          mkdir -p $ANDROID_HOME/tools/bin
          ln -s $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager $ANDROID_HOME/tools/bin/sdkmanager
          echo "创建了从旧路径到新路径的符号链接"
          
          # 验证符号链接
          echo "=== 符号链接验证 ==="
          ls -la $ANDROID_HOME/tools/bin/sdkmanager
          
          # 验证NDK
          echo "=== NDK验证 ==="
          ls -la $ANDROID_NDK_HOME/ndk-build || echo "NDK构建工具不存在"
          
          # 执行构建并捕获详细日志
          # 使用--force参数强制重新检查所有配置
          ANDROID_HOME=$ANDROID_HOME \
          ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT \
          ANDROID_NDK_HOME=$ANDROID_NDK_HOME \
          ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT \
          ANDROID_NDK=$ANDROID_NDK \
          PATH=$ANDROID_HOME/cmd
