name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Cython==0.29.33 buildozer

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK
        run: |
          # 设置 Android SDK 路径
          ANDROID_HOME=/usr/local/lib/android/sdk
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          
          # 创建目录结构
          sudo mkdir -p $ANDROID_HOME
          sudo chown -R runner:runner $ANDROID_HOME
          
          # 安装必要依赖
          sudo apt-get update && sudo apt-get install -y \
            unzip \
            libc6-i386 \
            lib32stdc++6 \
            lib32z1 \
            zlib1g-dev

          # 下载命令行工具
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-*.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          rm commandlinetools-linux-*.zip

          # 接受许可证
          mkdir -p $ANDROID_HOME/licenses
          echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license
          echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license

          # 安装组件
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME \
            "platform-tools" \
            "build-tools;33.0.2" \
            "platforms;android-33" \
            "cmdline-tools;latest"

          # 创建兼容旧版路径的目录结构
          mkdir -p $ANDROID_HOME/tools
          ln -s $ANDROID_HOME/cmdline-tools/latest/bin $ANDROID_HOME/tools/bin

      - name: Configure Buildozer
        run: |
          # 初始化 Buildozer 环境
          buildozer init
          
          # 修正 buildozer.spec 配置
          cat <<EOF >> buildozer.spec
          # 强制使用我们安装的 SDK
          android.sdk_path = /usr/local/lib/android/sdk
          android.ndk_path = $HOME/.buildozer/android/platform/android-ndk-r25b
          p4a.branch = develop
          android.accept_sdk_license = True
          log_level = 2
          
          # 应用配置
          title = MyApp
          package.name = pythonapp
          package.domain = com.example
          source.dir = .
          requirements = python3,kivy
          android.build_tools_version = 33.0.2
          android.api = 33
          EOF

      - name: Pre-download NDK
        run: |
          mkdir -p ~/.buildozer/android/platform
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip -d ~/.buildozer/android/platform/
          rm android-ndk-r25b-linux.zip

      - name: Build APK
        run: |
          # 验证环境
          echo "=== Buildozer 版本 ==="
          buildozer --version
          
          echo "=== Android 工具路径 ==="
          ls -la /usr/local/lib/android/sdk/build-tools/33.0.2/
          
          # 执行构建（使用完整命令格式）
          buildozer -v android debug build 2>&1 | tee build.log
          
          # 检查错误
          if grep -q "ERROR:" build.log; then
            echo "构建过程中发现错误！"
            cat build.log | grep "ERROR:"
            exit 1
          fi
          
          # 收集产物
          mkdir -p artifacts
          cp bin/*.apk artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifacts
          path: |
            artifacts/
            build.log
