name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Cython==0.29.33 buildozer

      - name: Set up JDK (必须使用 Java 17+)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK and accept licenses
        run: |
          # 设置 Android SDK 路径
          ANDROID_HOME=/usr/local/lib/android/sdk
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          
          # 安装必要工具
          sudo apt-get update && sudo apt-get install -y unzip
          
          # 下载兼容版本的命令行工具（旧版支持Java11）
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d /tmp/
          rm cmdline-tools.zip
          
          # 创建目录结构
          mkdir -p $ANDROID_HOME/cmdline-tools
          mv /tmp/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          
          # 配置环境变量
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_PATH
          
          # 安装组件（使用旧版语法）
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME \
            "platform-tools" \
            "build-tools;33.0.2" \
            "platforms;android-33"
          
          # 接受许可证
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Initialize Buildozer
        run: buildozer init

      - name: Modify buildozer.spec
        run: |
          sed -i 's/package.name = myapp/package.name = pythonapp/' buildozer.spec
          sed -i 's/package.domain = org.example/package.domain = com.example/' buildozer.spec
          sed -i 's/source.dir =.*/source.dir = ./' buildozer.spec
          sed -i 's/requirements =.*/requirements = python3,kivy/' buildozer.spec
          sed -i 's/main\.py/main.py/' buildozer.spec

      - name: Build APK
        run: |
          buildozer -v android debug
          mkdir -p artifacts
          cp bin/*.apk artifacts/

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app-apk
          path: artifacts/
