name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -y
          sudo apt-get install -y \
            unzip \
            libc6:i386 \
            libncurses6:i386 \
            libstdc++6:i386 \
            libz1:i386 \
            libx11-6:i386 \
            gcc-multilib \
            g++-multilib \
            autoconf \
            automake \
            libtool \
            openjdk-11-jdk \
            python3.8-dev \
            libbz2-dev \
            libdb-dev \
            libgdbm-dev \
            liblzma-dev \
            tk-dev \
            uuid-dev \
            libnsl-dev \
            libreadline-dev \
            libffi-dev \
            autoconf-archive \
            pkg-config  # 新增 pkg-config 工具

      - name: Create buildozer.spec
        run: |
          cat <<EOF > $GITHUB_WORKSPACE/buildozer.spec
          [app]
          title = MyApp
          package.name = pythonapp
          package.domain = com.example
          source.dir = .
          requirements = python3==3.8.6,kivy,libffi==3.4.4  # 指定 libffi 版本
          version = 0.1
          
          android.sdk_path = /usr/local/lib/android/sdk
          android.ndk_path = /usr/local/lib/android/sdk/ndk/25.2.9519653  # 固定 NDK 版本
          android.build_tools_version = 33.0.2
          android.api = 33
          android.minapi = 21
          android.ndk_api = 23
          android.accept_sdk_license = True
          android.archs = arm64-v8a,armeabi-v7a
          android.bootstrap = sdl2  # 明确指定 bootstrap
          android.private_storage = true
          android.use_sdl2 = true
          
          [buildozer]
          log_level = 2  # 调试日志级别
          warn_on_root = False
          EOF

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: ''

      - name: Install Android SDK and NDK
        run: |
          ANDROID_HOME=/usr/local/lib/android/sdk
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          
          # 安装指定版本 NDK（与 buildozer.spec 一致）
          sudo mkdir -p $ANDROID_HOME/ndk/25.2.9519653
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux-x86_64.zip -O /tmp/android-ndk.zip
          unzip -q /tmp/android-ndk.zip -d $ANDROID_HOME/ndk/25.2.9519653
          rm /tmp/android-ndk.zip
          
          # 安装 SDK 组件
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "tools" "build-tools;33.0.2" "platforms;android-33"
          
          # 更新环境变量
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Create symbolic links
        run: |
          sudo ln -sfn $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager $ANDROID_HOME/tools/bin/sdkmanager
          sudo ln -sfn $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager $ANDROID_HOME/tools/bin/avdmanager

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          # 固定 python-for-android 版本与 buildozer 兼容
          pip install cython==0.29.36 buildozer==1.5.0 python-for-android==2023.9.16

      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          buildozer -v android debug 2>&1 | tee build.log
          
          if [ -f bin/*.apk ]; then
            mkdir -p artifacts
            cp bin/*.apk artifacts/
          else
            echo "=== 构建失败 ==="
            cat build.log
            exit 1
          fi

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifact
          path: artifacts/*.apk

      - name: Upload build log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
