name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Cython==0.29.33 buildozer

      - name: Set up JDK (Java 11 required for Android)
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Android SDK and accept licenses (手动安装)
        run: |
          # 安装 Android SDK 命令行工具
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d /tmp/
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          mv /tmp/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/
          rm cmdline-tools.zip

          # 配置环境变量
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

          # 安装必要的 Android 组件
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "build-tools;33.0.2" "platforms;android-33" "platform-tools"
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Initialize Buildozer
        run: buildozer init

      - name: Modify buildozer.spec
        run: |
          sed -i 's/package.name = myapp/package.name = pythonapp/' buildozer.spec
          sed -i 's/package.domain = org.example/package.domain = com.example/' buildozer.spec
          sed -i 's/source.dir =.*/source.dir = ./' buildozer.spec
          sed -i 's/requirements =.*/requirements = python3,kivy/' buildozer.spec
          sed -i 's/main\.py/main.py/' buildozer.spec

      - name: Build APK
        run: |
          buildozer -v android debug
          mkdir artifacts
          cp bin/*.apk artifacts/

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app-apk
          path: artifacts/
