name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -y
          sudo apt-get install -y \
            unzip \
            libc6:i386 \
            libncurses6:i386 \
            libstdc++6:i386 \
            libz1:i386 \
            libx11-6:i386 \
            gcc-multilib \
            g++-multilib \
            autoconf \
            automake \
            libtool \
            openjdk-11-jdk \
            python3.8-dev \
            libbz2-dev \
            libdb-dev \
            libgdbm-dev \
            liblzma-dev \
            tk-dev \
            uuid-dev \
            libnsl-dev \
            libreadline-dev \
            autoupdate  # 新增 autoupdate 工具

      - name: Create buildozer.spec
        run: |
          cat <<EOF > $GITHUB_WORKSPACE/buildozer.spec
          [app]
          title = MyApp
          package.name = pythonapp
          package.domain = com.example
          source.dir = .
          requirements = python3==3.8.6,kivy
          version = 0.1
          
          android.sdk_path = /usr/local/lib/android/sdk
          android.ndk_path = /usr/local/lib/android/sdk/ndk/25.2.9519653
          android.build_tools_version = 33.0.2
          android.api = 33
          android.minapi = 21
          android.ndk_api = 23
          android.accept_sdk_license = True
          android.archs = arm64-v8a,armeabi-v7a
          android.sdkmanager = /usr/local/lib/android/sdk/tools/bin/sdkmanager
          android.avdmanager = /usr/local/lib/android/sdk/tools/bin/avdmanager
          
          [buildozer]
          log_level = 4  # 提高日志级别以便排查
          warn_on_root = False
          EOF

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: ''

      - name: Install Android SDK
        run: |
          ANDROID_HOME=/usr/local/lib/android/sdk
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          
          sudo rm -rf $ANDROID_HOME
          sudo mkdir -p $ANDROID_HOME/cmdline-tools/latest
          sudo chown -R runner:runner $ANDROID_HOME
          
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O /tmp/cmdline-tools.zip
          unzip -q /tmp/cmdline-tools.zip -d /tmp/cmdline-tools
          rsync -a /tmp/cmdline-tools/cmdline-tools/ $ANDROID_HOME/cmdline-tools/latest/
          rm -rf /tmp/cmdline-tools*

          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
          
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null
          
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "tools" "build-tools;33.0.2" "platforms;android-33" "ndk;25.2.9519653"

      - name: Create symbolic links
        run: |
          sudo mkdir -p /usr/local/lib/android/sdk/tools/bin
          sudo ln -sfn /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager /usr/local/lib/android/sdk/tools/bin/sdkmanager
          sudo ln -sfn /usr/local/lib/android/sdk/cmdline-tools/latest/bin/avdmanager /usr/local/lib/android/sdk/tools/bin/avdmanager

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          # 使用存在的 python-for-android 版本，如 2023.10.1 或最新稳定版
          pip install cython==0.29.36 buildozer==1.5.0 python-for-android==2023.10.1

      - name: Fix libffi autoconf issues (关键修复步骤)
        run: |
          # 等待 buildozer 生成 libffi 构建目录
          sleep 10  # 确保目录生成
          
          # 定位 libffi 目录（根据 buildozer 日志中的实际路径调整）
          LIBFFI_DIR=$(find $GITHUB_WORKSPACE/.buildozer/android/platform/ -name libffi -type d | head -n 1)
          
          if [ -z "$LIBFFI_DIR" ]; then
            echo "错误：未找到 libffi 目录"
            exit 1
          fi
          
          cd $LIBFFI_DIR
          echo "当前目录: $(pwd)"
          
          # 运行 autoupdate 修复过时宏
          autoupdate -i || true
          
          # 添加宏允许（解决 LT_SYS_SYMBOL_USCORE 未定义）
          echo "m4_pattern_allow([LT_SYS_SYMBOL_USCORE])" >> configure.ac
          
          # 重新生成配置文件
          autoreconf -fi || true

      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          buildozer -v android debug 2>&1 | tee build.log
          
          if [ -f bin/*.apk ]; then
            mkdir -p artifacts
            cp bin/*.apk artifacts/
          else
            echo "=== 构建失败 ==="
            cat build.log
            exit 1
          fi

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifact
          path: artifacts/*.apk

      - name: Upload build log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
